Bump all GHA package versions (#14)
Co-authored-by: github-actions <github-actions@github.com>

diff --git a/.github/workflows/wipac-cicd.yml b/.github/workflows/wipac-cicd.yml
--- a/.github/workflows/wipac-cicd.yml
+++ b/.github/workflows/wipac-cicd.yml
@@ -1,35 +1,56 @@
 name: ci/cd
 
-on: [ push ]
+on:
+  # only on branch pushes
+  push:
+    branches:
+      - '**'
+    tags-ignore:
+      - '**'
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  # don't cancel on main/master/default
+  cancel-in-progress: ${{ format('refs/heads/{0}', github.event.repository.default_branch) != github.ref }}
 
 jobs:
+
+  #############################################################################
+  # TOOLS FOR SETTING UP MATRIX-BASED JOBS
+  #############################################################################
 
   py-versions:
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.versions.outputs.matrix }}
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v5
+        with:
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
       - id: versions
-        uses: WIPACrepo/wipac-dev-py-versions-action@v2.5
+        uses: WIPACrepo/wipac-dev-py-versions-action@v2.7
 
   ###########################################################################
   # LINTERS
   ###########################################################################
 
-  #flake8:
-  #  needs: [ py-versions ]
-  #  runs-on: ubuntu-latest
-  #  strategy:
-  #    fail-fast: false
-  #    matrix:
-  #      py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
-  #  steps:
-  #    - uses: actions/checkout@v4
-  #    - uses: actions/setup-python@v5
-  #      with:
-  #        python-version: ${{ matrix.py3 }}
-  #    - uses: WIPACrepo/wipac-dev-flake8-action@v1.1
+#  flake8:
+#    needs: [ py-versions ]
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
+#    steps:
+#      - uses: actions/checkout@v5
+#        with:
+#          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
+#      - uses: actions/setup-python@v6
+#        with:
+#          python-version: ${{ matrix.py3 }}
+#      - uses: WIPACrepo/wipac-dev-flake8-action@v1.3
+#        with:
+#          max-complexity: 10  # ideal is ~10-15
 
   mypy:
     needs: [ py-versions ]
@@ -39,30 +60,52 @@ jobs:
       matrix:
         py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
     steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
+      - uses: actions/checkout@v5
+        with:
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
+          fetch-depth: 0  # setuptools-scm needs to access git tags
+      - uses: actions/setup-python@v6
         with:
           python-version: ${{ matrix.py3 }}
       - uses: WIPACrepo/wipac-dev-mypy-action@v2.0
+
 
   ###########################################################################
   # PACKAGING
   ###########################################################################
 
   py-setup:
+    if: ${{ github.actor != 'dependabot[bot]' }} # dependabot cannot access PAT
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v5
         with:
           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-      - uses: WIPACrepo/wipac-dev-py-setup-action@v4.2
+          ref: ${{ github.ref }}  # dont lock to sha (action needs to push)
+      - uses: WIPACrepo/wipac-dev-py-setup-action@v5.7
         with:
+          mode: PACKAGING_AND_PYPI
           python_min: 3.9
           pypi_name: icecube-voka
           author: IceCube
           author_email: developers@icecube.wisc.edu
-          keywords: |
-            "histogram comparison" "outlier detection" "statistical tests" "empirical p-value threshold" "poissonian statistics"
+          keywords_comma: IceCube, WIPAC, histogram comparison, outlier detection, statistical tests, empirical p-value threshold, poissonian statistics
+          auto_mypy_option: True
+
+  py-dependencies:
+    needs: [
+      # linters so we don't waste compute on faulty code...
+      # flake8,
+      mypy,
+    ]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v5
+        with:
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
+          fetch-depth: 0  # setuptools-scm needs to access git tags
+      - uses: WIPACrepo/wipac-dev-py-dependencies-action@v3.2
+
 
   ###########################################################################
   # TESTS
@@ -76,15 +119,21 @@ jobs:
       matrix:
         py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
     steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
+      - uses: actions/checkout@v5
+        with:
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
+          fetch-depth: 0  # setuptools-scm needs to access git tags
+      - uses: actions/setup-python@v6
         with:
           python-version: ${{ matrix.py3 }}
       - name: Setup Dependencies
         run: |
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           pip install --upgrade pip wheel setuptools
           pip install .[tests]
-      - run: |
+      - name: "python -m pytest test"
+        run: |
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           python -m pytest test
 
   ###########################################################################
@@ -94,25 +143,21 @@ jobs:
   release:
     # only run on main/master/default
     if: format('refs/heads/{0}', github.event.repository.default_branch) == github.ref
-    needs: [ mypy, py-setup, tests ]
-    runs-on: ubuntu-latest
-    concurrency: release  # prevent any possible race conditions
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      # Python-Package Version Bump
-      - uses: python-semantic-release/python-semantic-release@v9.8.1
-        id: psr-psr
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-      # PyPI Release
-      - uses: pypa/gh-action-pypi-publish@v1.13.0
-        if: steps.psr-psr.outputs.released == 'true'
-        with:
-          password: ${{ secrets.WIPAC_PYPI_TOKEN }}
-      # GitHub Release
-      - uses: python-semantic-release/upload-to-gh-release@v9.8.1
-        if: steps.psr-psr.outputs.released == 'true'
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+    needs: [
+      py-versions,
+      mypy,
+      # flake8,
+      py-setup,
+      py-dependencies,
+      tests,
+    ]
+    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/tag-and-release.yml@v1.16
+    permissions: # for GITHUB_TOKEN
+      contents: write
+    with:
+      project-type: python
+      python-version: "${{ fromJSON(needs.py-versions.outputs.matrix)[0] }}"
+      release-artifacts: |
+        py-dependencies-logs
+    secrets:
+      TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # trigger tag-event gha workflows
